# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Mediator"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'ttwkr'
author: 'ttwkr'
author_image: ""
remote_theme : dirkfabisch/mediator
paginate:	5

url: "https://ttwkr.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/ttwkr
    desc:	Fork me on github
    share_url:
    share_title:
    share_link: